export const WINDOW_RESIZE = 'WINDOW_RESIZE'
export const SET_LIST_PRODUCT = 'SET_LIST_PRODUCT'
export const SET_PRODUCT_BY_ID = 'SET_PRODUCT_BY_ID'
export const SET_COLORS = 'SET_COLORS'
export const SET_SIZES = 'SET_SIZES'
export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS'
export const SET_FILTER_PRODUCT = 'SET_FILTER_PRODUCT'
export const SET_SIZE_AND_QUANTITY_STOCK = 'SET_SIZE_AND_QUANTITY_STOCK'
export const SET_ALL_PRODUCT_IN_SHOP = 'SET_ALL_PRODUCT_IN_SHOP'
export const SAVE_CURRENT_QUANTITY = 'SAVE_CURRENT_QUANTITY'
export const SET_PRODUCT_IN_CART = 'SET_PRODUCT_IN_CART'
export const REMOVE_PRODUCT_IN_CART = 'REMOVE_PRODUCT_IN_CART'
export const GET_PRODUCT_IN_CART = 'GET_PRODUCT_IN_CART'
export const UPDATE_PROFILE_INDEX  = 'UPDATE_PROFILE_INDEX'
export const GET_PROFILE_INDEX  = 'GET_PROFILE_INDEX'
export const SET_ORDER_HISTORY = 'SET_ORDER_HISTORY'
export const SET_ORDER_DETAIL_HISTORY = 'SET_ORDER_DETAIL_HISTORY'
export const CHANGE_ADMIN_PAGE = 'CHANGE_ADMIN_PAGE'
export const SET_SUPPLIER = 'SET_SUPPLIER'
export const GET_SUPPLIER = 'GET_SUPPLIER'
export const SET_CATEGORY = 'SET_CATEGORY'
export const GET_CATEGORY = 'GET_CATEGORY'


/**
 * constant for messenge error
 */
 
 export const SET_MESSAGE_ADD_SUPPLIER = "SET_MESSAGE_ADD_SUPPLIER";
 export const SET_MESSAGE_ADD_CATEGORY = "SET_MESSAGE_ADD_CATEGORY";
 export const SET_MESSAGE_ADD_PRODUCT = "SET_MESSAGE_ADD_PRODUCT";
/**
 * constant for authentication
 */

 export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
 export const REGISTER_FAIL = "REGISTER_FAIL";
 export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
 export const LOGIN_FAIL = "LOGIN_FAIL";
 export const LOGOUT = "LOGOUT";
 
 export const SET_MESSAGE = "SET_MESSAGE";
 export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
 
 
