export const TOGGLE_NAV = 'TOGGLE_NAV'
export const WINDOW_RESIZE = 'WINDOW_RESIZE'
export const SET_LIST_PRODUCT = 'SET_LIST_PRODUCT'
export const SET_PRODUCT_BY_ID = 'SET_PRODUCT_BY_ID'
export const SET_COLORS = 'SET_COLORS'
export const SET_SIZES = 'SET_SIZES'
export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS'
export const SET_FILTER_PRODUCT = 'SET_FILTER_PRODUCT'
export const SET_SIZE_AND_QUANTITY_STOCK = 'SET_SIZE_AND_QUANTITY_STOCK'
export const SET_PRODUCT_BY_CATEGORY = 'SET_PRODUCT_BY_CATEGORY'
export const SAVE_CURRENT_QUANTITY = 'SAVE_CURRENT_QUANTITY'
export const SET_PRODUCT_IN_CART = 'SET_PRODUCT_IN_CART'
export const REMOVE_PRODUCT_IN_CART = 'REMOVE_PRODUCT_IN_CART'
export const SORTING_PRODUCT_BY_KEYWORD = 'SORTING_PRODUCT_BY_KEYWORD'
export const GET_PRODUCT_IN_CART = 'GET_PRODUCT_IN_CART'

/**
 * constant for authentication
 */

 export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
 export const REGISTER_FAIL = "REGISTER_FAIL";
 export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
 export const LOGIN_FAIL = "LOGIN_FAIL";
 export const LOGOUT = "LOGOUT";
 
 export const SET_MESSAGE = "SET_MESSAGE";
 export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
 
 
